variables:
  DOCKER_REGISTRY: registry.hamdocker.ir
  DOCKER_IMAGE: $DOCKER_REGISTRY/torob-bootcamp-1402/narges-montazeri-chatbot:${CI_COMMIT_SHORT_SHA}
  OPENAI_API_KEY: ${OPENAI_API_KEY}

stages:
  - "build"
  - "test"
  - "deploy"

build:
  services:
    - docker:dind
  tags:
    - bootcamp
    - fi
  stage: build
  image: docker:stable
  script:
    - mkdir -p ~/.docker && cat "$DOCKER_AUTH_CONFIG" > ~/.docker/config.json
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}

test:
  services:
    - name: docker.arvancloud.ir/ankane/pgvector:latest
      alias: postgres
  tags:
    - bootcamp
    - fi
  stage: test
  image: ${DOCKER_IMAGE}
  variables:
    POSTGRES_PASSWORD: supersecretpassword
    MEDIA_DIR: /media
    DB_HOST: postgres
    DB_PASS: supersecretpassword
  script:
    - python /app/myproject/manage.py migrate
    - python /app/myproject/manage.py test chatbot
    
deploy:
  tags:
    - bootcamp
    - ir
  stage: deploy
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - main
  script:
  - darkube deploy --token ${DEPLOY_TOKEN} --app-id ${APP_ID} --image-tag ${CI_COMMIT_SHORT_SHA}
