
variables:
  DOCKER_REGISTRY: registry.hamdocker.ir
  DOCKER_IMAGE: $DOCKER_REGISTRY/torob-bootcamp-1402/narges-montazeri-chatbot:${CI_COMMIT_SHORT_SHA}
  CONTAINER_NAME: "postgres"

stages:
  - "build"
  - "test"
  - "deploy"

build:
  services:
    - docker:dind
  tags:
    - bootcamp
    - fi
  stage: build
  image: docker:stable
  before_script:
    - mkdir -p ~/.docker && cat "$DOCKER_AUTH_CONFIG" > ~/.docker/config.json
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

test:
  services:
    - docker:dind
  tags:
    - bootcamp
    - fi
  stage: test
  image: docker:stable
  before_script:
    - mkdir -p ~/.docker && cat "$DOCKER_AUTH_CONFIG" > ~/.docker/config.json
  script:
    - docker pull $DOCKER_IMAGE
    - docker run --name $CONTAINER_NAME -e POSTGRES_DB=postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -d postgres:latest
    - docker run -it --rm --link $CONTAINER_NAME -e $DOCKER_IMAGE python /app/myproject/manage.py test
  after_script:
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true

deploy:
  tags:
    - bootcamp
    - ir
  stage: deploy
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - main
  script:
  - darkube deploy --token ${DEPLOY_TOKEN} --app-id ${APP_ID} --image-tag ${CI_COMMIT_SHORT_SHA}