stages:
  - "build"
  - "test"
  - "deploy"

build:
  services:
    - docker:dind
  tags:
    - bootcamp
    - fi
  stage: build
  image: docker:stable
  script:
    - mkdir -p ~/.docker && cat "$DOCKER_AUTH_CONFIG" > ~/.docker/config.json
    - docker build -t registry.hamdocker.ir/torob-bootcamp-1402/narges-montazeri-chatbot:${CI_COMMIT_SHORT_SHA} .
    - docker push registry.hamdocker.ir/torob-bootcamp-1402/narges-montazeri-chatbot:${CI_COMMIT_SHORT_SHA}

test:
  tags:
    - bootcamp
    - fi
  variables:
    OPENAI_API_KEY: ${OPENAI_API_KEY}
  stage: test
  image: registry.hamdocker.ir/torob-bootcamp-1402/narges-montazeri-chatbot:${CI_COMMIT_SHORT_SHA}
  script:
    - python /app/myproject/manage.py migrate
    - python /app/myproject/manage.py test
  

deploy:
  tags:
    - bootcamp
    - ir
  stage: deploy
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - main
  script:
  - darkube deploy --token ${DEPLOY_TOKEN} --app-id ${APP_ID} --image-tag ${CI_COMMIT_SHORT_SHA}