version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  chatbot:
    container_name: chatbot
    ports:
      - 8000:8000
    environment:
      MEDIA_DIR: /media
      DB_HOST: db
      DB_PASS: postgres
    depends_on:
      - db
    image: chatbot:latest

volumes:
  postgres_data:
    name: postgres_data 
