version: '3.3'

services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  chatbot:
    container_name: chatbot
    ports:
      - 8000:8000
    environment:
      MEDIA_DIR: /media
      DB_HOST: db
      DB_PASS: postgres
      # todo: remove it
      OPENAI_API_KEY: aThe1kygMkF3uncybaXxBh8disxq9yvi
    depends_on:
      - db
    volumes: 
      - chatbot_media:/media
    image: ${DOCKER_IMAGE}

volumes:
  postgres_data:
    name: postgres_data 
  chatbot_media:
    name: chatbot_media
